### ISSUE TITLE
HMR not working when Main Module is in a sub directory

### ISSUE THREAD

**Issue by dynajoe** [fluxxu/elm-hot-loader#4]
When you have a Main module nested a few folders deep it doesn't seem to pick up on changes.

For example

```
app/
   /src
     elm-package.json
      /Components
           /ComponentA
                 Main.elm
```

```
var Elm = require('./src/Components/ComponentA/Main')

var elm = Elm.fullscreen(Elm.Components.ComponentA.Main, { swap: false })
```

The above file configuration doesn't work. However, if I move the Main.elm up a few directories HMR works.

```
app/
   /src
     elm-package.json
     Main.elm
      /Components
           /ComponentA

```

**Comment by dynajoe** [comment]
this might help visualize: https://dl.dropboxusercontent.com/u/53664792/hmr-issue.gif

**Comment by fluxxu** [comment]
It's a bug of elm-hot-loader. I just published 0.1.5 to fix it.
Thanks!

**Comment by fluxxu** [comment]
Btw, what's the software you used to record this gif?
I used Gyazo and it only allows me to record several seconds...

**Comment by dynajoe** [comment]
I created the video using QuickTime screen recording. I then used the following gist: https://gist.github.com/dergachev/4627207

**Comment by dynajoe** [comment]
This doesn't seem to resolve the issue i'm witnessing. I'd be happy to show you on a google hangout?

**Comment by fluxxu** [comment]
Hi, could you try

```
var Elm = require('./src/Components/ComponentA/Main')

var elm = Elm.fullscreen(Elm.Components.ComponentA, { swap: false })
```

Thanks.

**Comment by fluxxu** [comment]
Closed. Feel free to reopen :)
